### ISSUE TITLE
Sudering Strike

### ISSUE THREAD

**Issue by russopie** [Owyn/no_more_wasted_grim-strikes#1]
Sudering Strike is cancelling Grim Strike, btw it's a very good module increased my DPS a lot. Thank you!!!

**Comment by Owyn** [comment]
![default](https://user-images.githubusercontent.com/1309656/44050049-79e14038-9f3e-11e8-983f-6eb5ecf5a858.png)
yea it does...
glad you like it ☺️

**Comment by Owyn** [comment]
added support for sundering in latest update, now it wouldn't cancel grims with it 😸
