### ISSUE TITLE
Color is not always set back

### ISSUE THREAD

**Issue by Kagu-chan** [Owyn/no_more_wasted_grim-strikes#2]
Hi,

the color of the icons is not always set back - ran ten minutes with red double shear :o - so i removed the command locally. Would like an option to disable the color function completely since its only visual and especially while streaming not the best idea :D

Besides that... it helps really since i see how early i've cancelled...

Question:
Does it take ATK-Speed into account? It feel'd a bit clumsy from time to time...

**Comment by Owyn** [comment]
it doesn't set back if you missed the target... and then didn't use any other skill other than sheer\grim

It takes only ping into account, when number for the first hit of the skill is received - it removes red icon overlay

might also be just today's update module wasn't prepared for, try with updated module and reopen the issue if it persists,

I'm surprised it worked at all without update...

**Comment by Owyn** [comment]
btw, you can disable color by removing the opcode for it from your protocol file `\Tera-Proxy\node_modules\tera-data\map\protocol.335640.map` (for example)
that way it won't be necessary to edit the script or turn the autoupdate off

**Comment by Owyn** [comment]
> Would like an option to disable the color function completely since its only visual and especially while streaming not the best idea :D

added such option
