### ISSUE TITLE
86

### ISSUE THREAD

**Issue by gzosiek21** [Owyn/no_more_wasted_grim-strikes#3]
[00:45:32.457] [dispatch] [no_more_wasted_grim-strikes] handle: error running hook for S_LOGIN<14>
hook: (anonymous) in no_more_wasted_grim-strikes
data: {
  templateId: 11009,
  gameId: 14073yr5yr574546y756754908584565ryf794n,
  serverId: 38,
  playerId: 535639054565657,
  actionMode: 0,
  alive: true,
  status: 0,
  walkSpeed: 50,
  runSpeed: 190,
  appearance: Customize {
    unk: 101,
    skinColor: 30,
    faceStyle: 11,
    faceDecal: 1,
    hairStyle: 9,
    hairColor: 25,
    voice: 4,
    tattoos: 0
  },
  visible: true,
  isSecondCharacter: false,
  level: 66,
  awakeningLevel: 0,
  profMineral: 0,
  profBug: 0,
  profHerb: 0,
  profEnergy: 0,
  profPet: 1,
  pkDeclareCount: 0,
  pkKillCount: 0,
  totalXp: 4872714735n,
  levelXp: 156524655n,
  totalLevelXp: 14641642200n,
  epLevel: 365,
  epXp: 2705458n,
  epDailyXp: 1023,
  restBonusXp: 286405664n,
  maxRestBonusXp: 322116128n,
  xpBonusPercent: 1,
  dropBonusPercent: 0,
  weapon: 88380,
  body: 88359,
  hand: 88366,
  feet: 88369,
  underwear: 179026,
  head: 88425,
  face: 88634,
  serverTime: 54206619n,
  isPkServer: true,
  chatBanEndTime: 0n,
  title: 0,
  weaponModel: 0,
  bodyModel: 0,
  handModel: 0,
  feetModel: 0,
  weaponDye: 0,
  bodyDye: 0,
  handDye: 0,
  feetDye: 0,
  underwearDye: 0,
  styleBackDye: 0,
  styleHeadDye: 0,
  styleFaceDye: 0,
  weaponEnchant: 0,
  isWorldEventTarget: false,
  infamy: 0,
  showFace: true,
  styleHead: 0,
  styleFace: 0,
  styleBack: 0,
  styleWeapon: 91600,
  styleBody: 91503,
  styleFootprint: 0,
  styleBodyDye: 0,
  showStyle: true,
  titleCount: 0n,
  appearance2: 100,
  scale: 1,
  guildLogoId: 0,
  name: 'yourMom',
  details: <Buffer 0d 13 1a 08 00 00 00 00 1f 0a 04 00 17 0a 00 00 09 00 0c 0d 00 00 00 00 15 1f 0e 16 1d 10 10 00>,
  shape: <Buffer 01 13 10 13 13 10 13 13 13 0f 0f 0f 0f 0f 0f 0f 10 13 0a 00 05 0b 10 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ... 14 more bytes>,
  servants: [
    { dbid: 442782n, id: 73, type: 0, energy: 100, slot: 0 },
    { dbid: 442783n, id: 70, type: 0, energy: 100, slot: 1 },
    { dbid: 442784n, id: 74, type: 0, energy: 100, slot: 2 },
    { dbid: 442791n, id: 600, type: 0, energy: 100, slot: 3 }
  ]
}
error: [dispatch] [no_more_wasted_grim-strikes] hook: Error: obsolete definition (S_EACH_SKILL_RESULT.13)
    at hook (C:\Users\a\AppData\Local\Programs\TeraToolbox\mods\wasted\index.js:147:23)
    at Object.callback (C:\Users\a\AppData\Local\Programs\TeraToolbox\mods\wasted\index.js:82:5)[00:45:32.457] [dispatch] [no_more_wasted_grim-strikes] handle: error running hook for S_LOGIN<14>
hook: (anonymous) in no_more_wasted_grim-strikes
data: {
  templateId: 11009,
  gameId: 14045673749546085874564594n,
  serverId: 38,
  playerId: 5324323345945057,
  actionMode: 0,
  alive: true,
  status: 0,
  walkSpeed: 50,
  runSpeed: 190,
  appearance: Customize {
    unk: 101,
    skinColor: 30,
    faceStyle: 11,
    faceDecal: 1,
    hairStyle: 9,
    hairColor: 25,
    voice: 4,
    tattoos: 0
  },
  visible: true,
  isSecondCharacter: false,
  level: 66,
  awakeningLevel: 0,
  profMineral: 0,
  profBug: 0,
  profHerb: 0,
  profEnergy: 0,
  profPet: 1,
  pkDeclareCount: 0,
  pkKillCount: 0,
  totalXp: 4872714735n,
  levelXp: 156524655n,
  totalLevelXp: 14641642200n,
  epLevel: 365,
  epXp: 2705458n,
  epDailyXp: 1023,
  restBonusXp: 286405664n,
  maxRestBonusXp: 322116128n,
  xpBonusPercent: 1,
  dropBonusPercent: 0,
  weapon: 88380,
  body: 88359,
  hand: 88366,
  feet: 88369,
  underwear: 179026,
  head: 88425,
  face: 88634,
  serverTime: 54206619n,
  isPkServer: true,
  chatBanEndTime: 0n,
  title: 0,
  weaponModel: 0,
  bodyModel: 0,
  handModel: 0,
  feetModel: 0,
  weaponDye: 0,
  bodyDye: 0,
  handDye: 0,
  feetDye: 0,
  underwearDye: 0,
  styleBackDye: 0,
  styleHeadDye: 0,
  styleFaceDye: 0,
  weaponEnchant: 0,
  isWorldEventTarget: false,
  infamy: 0,
  showFace: true,
  styleHead: 0,
  styleFace: 0,
  styleBack: 0,
  styleWeapon: 91600,
  styleBody: 91503,
  styleFootprint: 0,
  styleBodyDye: 0,
  showStyle: true,
  titleCount: 0n,
  appearance2: 100,
  scale: 1,
  guildLogoId: 0,
  name: 'yourMom',
  details: <Buffer 0d 13 1a 08 00 00 00 00 1f 0a 04 00 17 0a 00 00 09 00 0c 0d 00 00 00 00 15 1f 0e 16 1d 10 10 00>,
  shape: <Buffer 01 13 10 13 13 10 13 13 13 0f 0f 0f 0f 0f 0f 0f 10 13 0a 00 05 0b 10 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ... 14 more bytes>,
  servants: [
    { dbid: 442782n, id: 73, type: 0, energy: 100, slot: 0 },
    { dbid: 442783n, id: 70, type: 0, energy: 100, slot: 1 },
    { dbid: 442784n, id: 74, type: 0, energy: 100, slot: 2 },
    { dbid: 442791n, id: 600, type: 0, energy: 100, slot: 3 }
  ]
}
error: [dispatch] [no_more_wasted_grim-strikes] hook: Error: obsolete definition (S_EACH_SKILL_RESULT.13)
    at hook (C:\Users\a\AppData\Local\Programs\TeraToolbox\mods\wasted\index.js:147:23)
    at Object.callback (C:\Users\a\AppData\Local\Programs\TeraToolbox\mods\wasted\index.js:82:5)

**Comment by Owyn** [comment]
fixed just now, thx for the report
